apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "debezium.name" . }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.connect.storage.size }}
  storageClassName: standard