apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debezium.name" . }}-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
type: Opaque
stringData:
{{- with .Values.connect.secret }}
  {{- toYaml . | nindent 2 }}
{{- end}}

