apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.connect.name }}-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
type: Opaque
stringData:
{{- with .Values.connect.secret }}
  {{- toYaml . | nindent 2 }}
{{- end}}

